name: Linter

on: [push]

jobs:
  svlint:
    name: Check Style Conventions using svlint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create Build Directory
      run: mkdir build
    - name: Download svlint
      run: wget -O build/svlint.zip https://github.com/dalance/svlint/releases/download/v0.9.0/svlint-v0.9.0-x86_64-lnx.zip
    - name: Install svlint
      run: |
        unzip build/svlint.zip -d build
        echo "${PWD}/build/bin" >> $GITHUB_PATH
    - name: Check svlint installed
      run: svlint --version
    - name: Lint files
      run: tools/lint.sh
    - name: Cleanup
      run: rm -r build 
  verible:
    name: Check Style Conventions using Verible
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        config_file: '.verible-lint'
        paths: |
          ./src
        extra_args: "--waiver_files=.verible-waiver"